July_Soundcheck/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => 'static_pages#home'

  resources :sessions
  resources :reviews
  resources :albums
  resources :artists
  resources :users

end

July_Soundcheck/app/views/layouts/_global_search_bar.html.erb
<!--<ul class="global-search-bar">-->

  <!--<li class="field">
      <input data-typeahead-global id="global-search" type="text" placeholder="Search artists and albums">
      <input id="global-search" type="text" placeholder="Search artists and albums">
  </li>-->
  <li><input type="search" placeholder="Search artists & albums"></li>
  <li><button type="button" class="button hide-for-medium-down">Search</button></li>

<!--</ul>-->

July_Soundcheck/app/views/layouts/_user_menu.html.erb
<% if current_user %>
  <%= link_to current_user.displayname, current_user, data: { dropdown: "hover1", options: "is_hover:false; hover_timeout:333"}%>
  <ul class="dropdown menu-icon">
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Activity Feed", current_user %></li>
    <li><%= link_to "Settings", current_user %></li>
    <li class="divider"></li>
    <li><%= link_to "Log out", logout_path %></li>
  </ul>
<%end%>

July_Soundcheck/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "July Soundcheck" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav data-topbar class="top-bar">
      <section class="top-bar-section">
        <ul class="left">
          <li class="has-dropdown large">
            <a class = "active" data-dropdown="hover2" data-options: "is_over:false;">JSC</a>
            <ul class="dropdown hide-for-large-up">
              <li class = "active"><%= link_to "WRITE A REVIEW", new_review_path%></li>
              <li class = ""><%= link_to "Reviews", reviews_path %></li>
              <li class = ""><%= link_to "Artists", artists_path %></li>
              <li class = ""><%= link_to "Albums", albums_path %></li>
              <ul class="hide-for-large-up">
                <%= render partial: 'layouts/global_search_bar' %>
              </ul>
              <li class = "divider"></li>
              <li class = " has-dropdown large">
                <%= render partial: 'layouts/user_menu' %>
              </li>
            </ul>
          <li class = "hide-for-medium-down"> <%= link_to "Reviews", reviews_path%></li>
          <li class = "hide-for-medium-down"> <%= link_to "Artists", artists_path%></li>
          <li class = "hide-for-medium-down"> <%= link_to "Albums", albums_path%></li>
          <%= render partial: 'layouts/global_search_bar' %>
          <li>
          </li>
        </ul>
        <ul class = "right">
          <% if current_user %>
            <li class="active"><%= link_to "WRITE A REVIEW", new_review_path%></li>
            <li class="has-dropdown large">
              <%= render partial: 'layouts/user_menu' %>
            </li>
          <% else %>
            <li><%= link_to "Log in", new_session_path %></li>
            <li><%= link_to "Register", new_user_path %></li>
          <% end %>
        </ul>
      </section>
    </nav>
    <div class="row">
  <div class="large-12 small-centered columns"><%= yield %></div>
</div>
    <%= javascript_include_tag "application" %>
  </body>
</html>