July_Soundcheck/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => 'static_pages#home'

  resources :sessions
  resources :reviews
  resources :albums
  resources :artists
  resources :users

end

July_Soundcheck/app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
#  validates_uniqueness_of :name

  def average_review
    ave = 0.0
    count = review_count {|r| ave += r.rating}
    ave = ave / count unless count < 1
    ave.round(2)
  end

  def review_count
    count = 0
    albums.each do |a|
      a.reviews.each do |r|
        count += 1
        yield r if block_given?
      end
    end
    count
  end

  #This doesn't work yet 1/7
  def best_album
    best = albums[0]
    best_review = best.average_review
    albums.each do |a|
      if a.average_review > best_review
        best_review = a.average_review
        best = a
      end
    end
    best
  end
end

July_Soundcheck/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all.page(params[:page]).per_page(20)
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

July_Soundcheck/app/helpers/artists_helper.rb
module ArtistsHelper
end

July_Soundcheck/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, data: { typeahead: '', highlight: 'true', 'min-length': '1', hint: 'Enter something...', source: 'names' } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

July_Soundcheck/app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

July_Soundcheck/app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing <%= @artists.count %> Artists</h2>

<div class="large-12 columns">
  <%= will_paginate @artists, previous_label: h("<"),next_label: h(">") %><br>
</div>
<row>
  <table class="hover">
    <thead>
      <tr>
        <th width = "25%">Name</th>
        <th class = "text-center" width = "12.5%">Albums</th>
        <th width = "25%">Highest Rated Album</th>
        <th class = "text-center" width = "6.25%">Reviews</th>
        <th class = "text-center" width = "12.5%">Average Review</th>
      </tr>
    </thead>

    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td width = "25%"><%= link_to artist.name, artist %></td>
          <td class = "text-center" width = "12.5%"><%= artist.albums.count %></td>
          <td width = "12.5%"><%= link_to artist.best_album.title, artist.best_album %> (<%=artist.best_album.average_review %>)</td>
          <td class = "text-center" width = "12.5%"><%= artist.review_count %></td>
          <td class = "text-center" width = "12.5%"><%= artist.average_review %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="large-12 columns">
    <%= will_paginate @artists, previous_label: h("<"),next_label: h(">") %><br>
  </div>
</row>

July_Soundcheck/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

July_Soundcheck/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @artist.name %></h1>
  <h3>Top Rated Album</h3>
  <%= link_to @artist.best_album.title, @artist.best_album%>
  <h3>Albums</h3>
  <% @artist.albums.each do |fluh| %>
  <%= link_to fluh.title, fluh %><br>
  <% end %>
</p>



<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>