July_Soundcheck/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root :to => 'static_pages#home'

  resources :sessions
  resources :reviews
  resources :albums
  resources :artists
  resources :users

end

July_Soundcheck/app/models/album.rb
class Album < ActiveRecord::Base
  has_many :reviews
  belongs_to :artist
  accepts_nested_attributes_for :artist
  #validates_uniqueness_of :title

  def average_review
    ave = 0
    each_review { |r| ave += r.rating}
    ave /= reviews.count
    ave
  end

  def highest_review
    high = 0
    each_review { |r| high = r.rating if r.rating > high }
    high
  end

  def lowest_review
    low = 6
    each_review { |r| low = r.rating if r.rating < low }
    low
  end

  def each_review
    reviews.each do |r|
      yield r
    end
  end


  def album_params
    params.require(:album).permit(:name,:artist)
  end

end

July_Soundcheck/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all.page(params[:page]).per_page(20)
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name)
    end
end

July_Soundcheck/app/helpers/albums_helper.rb
module AlbumsHelper
end

July_Soundcheck/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

July_Soundcheck/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

July_Soundcheck/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing <%= @albums.count %> albums</h2>

<row>
  <div class="large-12 columns">
    <%= will_paginate @albums, previous_label: h("<"),next_label: h(">") %><br>
  </div>
  <table>
    <thead>
      <tr>
        <th width = "40%" >Album Name</th>
        <th width = "40%" >Artist Name</th>
        <th width = "10%" class="text-center">Reviews</th>
        <th width = "10%" class="text-center">Average Review</th>
      </tr>
    </thead>

    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td width = "40%" ><%= link_to album.title, album %></td>
          <td width = "40%" ><%= link_to album.artist.name, album.artist %></td>
          <td width = "10%" class="text-center"><%= album.reviews.count %></td>
          <td width = "10%" class="text-center">
            <%= album.average_review %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="large-12 columns">
    <%= will_paginate @albums, previous_label: h("<"),next_label: h(">") %><br>
  </div>
</row>

July_Soundcheck/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

July_Soundcheck/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<%console%>
<h1><%=link_to @album.artist.name, @album.artist%></h1>
<h3>
  <%= @album.title %>
</h3>
<h4> Reviews </h4>
<table>
  <tr>
    <th>Reviewer</th>
    <th>Rating</th>
    <th>Review</th>
  </tr>
<% @album.reviews.each do |review|%>
  <tr>
    <td><%= link_to review.user.displayname, review.user%></th>
    <td><%= review.rating %></th>
    <td><%= review.contents %></th>
    <td></th>
  </tr>
<% end %>
</table>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>